import { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    title: "Premium Wireless Headphones",
    price: 129.99,
    description: "High-quality wireless headphones with noise cancellation",
    category: "electronics",
    image: "https://via.placeholder.com/300x300?text=Headphones",
    rating: { rate: 4.5, count: 120 },
  },
  {
    id: 2,
    title: "Eco-Friendly Water Bottle",
    price: 34.99,
    description: "Sustainable stainless steel water bottle, keeps drinks cold for 24 hours",
    category: "accessories",
    image: "https://via.placeholder.com/300x300?text=Water+Bottle",
    rating: { rate: 4.7, count: 89 },
  },
  {
    id: 3,
    title: "Smart Watch Pro",
    price: 249.99,
    description: "Advanced fitness tracking with heart rate monitor and GPS",
    category: "electronics",
    image: "https://via.placeholder.com/300x300?text=Smart+Watch",
    rating: { rate: 4.3, count: 256 },
  },
  {
    id: 4,
    title: "Organic Cotton T-Shirt",
    price: 24.99,
    description: "100% organic cotton comfortable everyday t-shirt",
    category: "clothing",
    image: "https://via.placeholder.com/300x300?text=T-Shirt",
    rating: { rate: 4.2, count: 145 },
  },
  {
    id: 5,
    title: "Professional Camera Tripod",
    price: 89.99,
    description: "Lightweight aluminum tripod with phone holder mount",
    category: "accessories",
    image: "https://via.placeholder.com/300x300?text=Tripod",
    rating: { rate: 4.6, count: 78 },
  },
  {
    id: 6,
    title: "4K Webcam",
    price: 159.99,
    description: "Ultra HD webcam perfect for streaming and video calls",
    category: "electronics",
    image: "https://via.placeholder.com/300x300?text=Webcam",
    rating: { rate: 4.4, count: 203 },
  },
  {
    id: 7,
    title: "Bamboo Desk Organizer",
    price: 39.99,
    description: "Sustainable bamboo organizer for a clean workspace",
    category: "accessories",
    image: "https://via.placeholder.com/300x300?text=Desk+Organizer",
    rating: { rate: 4.5, count: 92 },
  },
  {
    id: 8,
    title: "Wireless Charging Pad",
    price: 44.99,
    description: "Fast charging pad compatible with all Qi-enabled devices",
    category: "electronics",
    image: "https://via.placeholder.com/300x300?text=Charger",
    rating: { rate: 4.3, count: 167 },
  },
  {
    id: 9,
    title: "Premium Running Shoes",
    price: 119.99,
    description: "Comfortable athletic shoes with superior cushioning",
    category: "clothing",
    image: "https://via.placeholder.com/300x300?text=Running+Shoes",
    rating: { rate: 4.6, count: 234 },
  },
  {
    id: 10,
    title: "Portable Power Bank",
    price: 54.99,
    description: "20000mAh power bank with fast charging support",
    category: "electronics",
    image: "https://via.placeholder.com/300x300?text=Power+Bank",
    rating: { rate: 4.7, count: 189 },
  },
  {
    id: 11,
    title: "Yoga Mat",
    price: 29.99,
    description: "Non-slip yoga mat for comfortable practice sessions",
    category: "accessories",
    image: "https://via.placeholder.com/300x300?text=Yoga+Mat",
    rating: { rate: 4.4, count: 156 },
  },
  {
    id: 12,
    title: "Bluetooth Speaker",
    price: 74.99,
    description: "Portable speaker with 360-degree sound and 12-hour battery",
    category: "electronics",
    image: "https://via.placeholder.com/300x300?text=Speaker",
    rating: { rate: 4.5, count: 298 },
  },
];

export const MOCK_CATEGORIES = [
  "electronics",
  "accessories",
  "clothing",
];
